export const PREPARE_CONSENT_REQUEST = 'PREPARE_CONSENT_REQUEST';
export const SET_CONSENT_ERROR = 'SET_CONSENT_ERROR';
export const SET_CONSENT_SUCCESS = 'SET_CONSENT_SUCCESS';
export const UPDATE_CONSENT_SUCCESS = 'UPDATE_CONSENT_SUCCESS';
export const UPDATE_CONSENT_ERROR = 'UPDATE_CONSENT_ERROR';
export const GET_ALL_CONSENTS_SUCCESS = 'GET_ALL_CONSENTS_SUCCESS';
export const GET_ALL_CONSENTS_ERROR = 'GET_ALL_CONSENTS_ERROR';
